name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag viralvariance/allinone:latest
    - name : login to docker
      run: docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - name: Push Docker image 
      run: docker push viralvariance/allinone:latest
